### ISSUE TITLE
Unpublish can-define@1.0.6

### ISSUE THREAD

**Issue by Bajix** [canjs/can-define#113]
can-define@1.0.6 creates a dependency graph with multiple versions of can-cid. can-util will load in 1.x, whereas can-define 0.x.

This throws an error w/ can-namespace, meaning this will break existing builds until fixed and will be automatically upgraded to.

can-define needs can-cid 1.x

**Comment by phillipskevin** [comment]
`can-define@1.0.6` has been deprecated.
