### ISSUE TITLE
Add lodash integration on can-define/list ~5

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-define#13]
From https://github.com/canjs/canjs/issues/192.  This should probably be another repo, but now that `.length` is observable on lists, this should be pretty easy to accomplish.  Lodash might just work.

Also related:
- https://github.com/canjs/canjs/issues/1939 - https://github.com/canjs/canjs/issues/1939

**Comment by justinbmeyer** [comment]
@liztom got started on this a tiny bit.

**Comment by liztom** [comment]
https://github.com/canjs/can-define-lodash

**Comment by justinbmeyer** [comment]
Closing as this will be possible with `can-observe`.
