### ISSUE TITLE
New changes to internal `get` doesn't support async setters 

### ISSUE THREAD

**Issue by DesignByOnyx** [canjs/can-define#132]
It's stated in the commit message (#130) that async setters aren't supported, and it's causing our code to break. The error is **`setVal` isn't a function** - happens inside of an async setter.

**Comment by justinbmeyer** [comment]
Why does the code have a default value AND an async setter?

Please point to the code.  Also, can you check for the existence of `setVal` in your setter?

**Comment by DesignByOnyx** [comment]
I pointed to code (see referenced issue above), and we can check for `setVal` - but we didn't need to yesterday. I now have to check every async setter in our app to make sure the same problem doesn't exist elsewhere. The "correctness" of our implementation is a separate discussion. The main issue is that code stopped working with no indication why. Had I not looked at the internals of can-define I wouldn't have known whether my code was bad or a breaking change was merged into can-define.

**Comment by phillipskevin** [comment]
Does `setVal` only not exist when the `value: null` is being set? Would removing [this line](https://github.com/donejs/bitcentive/blob/staging/public/components/select-contribution-month/select-contribution-month.js#L11) fix the issue?

I agree that it's bad that a patch release broke your code, so I'm not necessarily suggesting that is the fix. Just asking to understand the issue.
