### ISSUE TITLE
setter with default value bug call stack exceeded

### ISSUE THREAD

**Issue by roemhildtg** [canjs/can-define#142]
http://jsbin.com/nubigudequ/1/edit?html,js,console,output

I'm afraid the functionality introduced in here: https://github.com/canjs/can-define/issues/87 has resulted in another bug. 

If I have a simple setter like the one below that checks the previous set value, it results in a recursive loop of get/set. 

```javascript
let a = can.DefineMap.extend('a', {
  val: {
    value: 'hello',
    set(val){
      console.log(this.val); // tries to get the value, results in call stack error
      console.log('val set ' +  val);
      return val;
    }
  }
});
```

**Comment by phillipskevin** [comment]
I've added a test for this here: https://github.com/canjs/can-define/tree/default-value-setter-infinite-loop.

**Comment by phillipskevin** [comment]
@roemhildtg the fix for this is released: https://github.com/canjs/can-define/releases/tag/v1.0.16 is out
