### ISSUE TITLE
warn if `value` is set to an object type

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-define#148]
@justinbmeyer commented on [Fri Feb 17 2017](https://github.com/canjs/canjs/issues/3012)

like in this example: http://forums.donejs.com/t/data-binding-multi-select-with-data-transformed/554

**Comment by chasenlehara** [comment]
Related forum post: http://forums.donejs.com/t/can-define-value-vs-value/581

**Comment by bgando** [comment]
### emits warning in dev env
dev.warn("value is set to an object, but should only be set to a function or primitive type.")
```
vm = DefineMap.extend({
  options: {
    value: {}
  }
});
vm = DefineMap.extend({
  options: {
    value: []
  }
});
```
### correct way
```
vm = DefineMap.extend({
  options: {
    value: function(){ return {}; }
  }
});

vm = DefineMap.extend({
  options: {
    value: 2
  }
});
```
### Should I also update [these docs](https://canjs.com/doc/can-define.types.value.html)?
Should say any primitive type value, not any value.
![image](https://user-images.githubusercontent.com/3348231/29888874-52a580c6-8d90-11e7-930f-1412baa70f1a.png)

**Comment by phillipskevin** [comment]
I think this should say something like
> The value for `options` is set to an object. This will be shared by all instances of the DefineMap. Use a function that returns the object instead so each instance will get its own copy

This is probably too verbose, but something like this is what we need to explain.

We should not update the docs, because the API does still support passing objects as the `value` (and we don't want to break the API for this). We just want to warn people because this is usually not what you want.
