### ISSUE TITLE
Length is NOT fired if a property of the list is set.

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-define#150]
<img width="1193" alt="cursor_and_canjs_-_length" src="https://cloud.githubusercontent.com/assets/78602/23335743/3e882a40-fb81-11e6-8091-76853b0ec499.png">

**Comment by ilyavf** [comment]
Do you mean a list item by `property` of a list? (or an expando)

I can see that if i replace an item then `length` event is triggered twice (see https://github.com/canjs/can-define/issues/152)

**Comment by justinbmeyer** [comment]
```
list = new DefineList(["a","b","c"])
list.set(1,"B")
```
