### ISSUE TITLE
.value functions should not be observable

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-define#162]
If they are observable and invoked as part of a template, big problems can happen.

The solution is just to make sure 

1. Observation.add should not be called if `this.__inSetup` is true: https://github.com/canjs/can-construct/blob/master/can-construct.js#L280

2. We should wrap `value` with `Observation.ignore`.

**Comment by justinbmeyer** [comment]
http://jsbin.com/yafajal/edit?html,js,output

Also related ... we should check the number of dependencies in the observation.

**Comment by justinbmeyer** [comment]
Also, we can probably avoid `.getCurrent()` if `this.__inSetup` is true: https://github.com/canjs/can-define/blob/master/can-define.js#L280

**Comment by justinbmeyer** [comment]
```js
var DriversListVM = can.DefineMap.extend({
  drivers: {
    value: function(){
      return new can.DefineList([
        { title: "Dr.", first: "Cosmo", last: "Kramer", licensePlate: "A$$M^N" },
        { title: "Ms.", first: "Elaine", last: "Benes", licensePlate: "621433" }
     ])
    }
  },
  selected: {
    value: false
  },
  select: function(driver){
    this.selected = driver;
  }
})
```

```js
var func = function(){};

func = Observation.ignore(func);

func();
```

**Comment by justinbmeyer** [comment]
```js
return function(newVal) {
  if( this._inSetup ) {
    setData.call(this, newVal);
  } else {

	var current = getCurrent.call(this);
	if (newVal !== current) {
	  setData.call(this, newVal);

	canEvent.dispatch.call(this, {
						type: prop,
						target: this
	  }, [newVal, current]);
	}
  }
}
```

**Comment by justinbmeyer** [comment]
https://github.com/canjs/can-define/blob/master/can-define.js#L178 

```js
getInitialValue = Observation.ignore( make.get.defaultValue(prop, definition, typeConvert, eventsSetter) );
```

**Comment by bmomberger-bitovi** [comment]
It turns out we couldn't avoid `getCurrent` because that was responsible for executing the getter applied by `replaceWith` before trying to set the value.  However, that doesn't mean that we can't `Observation.ignore` it.
