### ISSUE TITLE
Batches aren't guaranteed to finish in DefineMap.setProps

### ISSUE THREAD

**Issue by bmomberger-bitovi** [canjs/can-define#170]
https://github.com/canjs/can-define/blob/master/map/map.js#L81 is not wrapped in a try/catch/finally block.  This is not an issue if all property sets complete normally.  However, if any property set throws an exception in the loop before that line, the stack will unwind past this point and not call `canBatch.stop()`.  This leads to broken page functionality, as all other actions are queued

Solution: wrap the entirety of the function between `canBatch.start()` and `canBatch.stop()`, exclusive, in a `try` block, and wrap the `canBatch.stop()` in a `finally` block.

JSBin: https://jsbin.com/sekohatiho/1/edit?html,js,output

__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Steps to reproduce:__

1. Create a sealed DefineMap (by subclassing the constructor before constructing).
2. Use `.set(Object)` on the map to attempt to set a property that is not defined on it.
3. Error is thrown.
4. Observe `can-event/batch.transactions`

__Expected results:__

3.  Batch transactions should be 0. (indicating transactions are flushed)

__Actual results:__

3. Batch transactions are 1. (indicating transactions are queued with no flush)

__Environment:__

| Software                   | Version
| -------------------- | -------
| can-define version   | 1.0.17
| Browser                    | Chrome 57
| Operating system    | MacOS Sierra 12.3

**Comment by cherifGsoul** [comment]
Related issue https://github.com/canjs/can-observation/issues/27

**Comment by justinbmeyer** [comment]
Closing for: canjs/can-observation#27
