### ISSUE TITLE
“Attempting to define property on object that is not extensible” error message not helpful

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-define#171]
Demo: http://jsbin.com/weseyaluca/1/edit?html,js,console,output

In that demo, an input is bound to `property` but it’s not defined in the view model. The error message should provide more useful information, such as what property is being defined, or a link to more info about the error, or really anything that will make it easier for someone to figure out what’s wrong with their code.

**Comment by justinbmeyer** [comment]
This error is caused by JS's internals.  It's not really something we have control over.  We might be able to handle this in `can-stache-bindings`, but there's nothing we can do in `can-define`.  Please move to `can-stache-bindings`.

**Comment by jeroencornelissen** [comment]
Recently we’re getting this error:
`Uncaught TypeError: Cannot define property ($click), object is not extensible`
Because we have a `($click)` event on a component tag.

```
<my-comp ($click)=“triggerEvent(…)” />
```

Is that related to this issue?
I can solve it with `seal: false`, but that doesn't seem right.
