### ISSUE TITLE
Revisit getCurrent call being made during define.setup

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-define#185]
This [`getCurrent`](https://github.com/canjs/can-define/blob/master/can-define.js#L291) call was added in https://github.com/canjs/can-define/pull/184 to prevent an error due to `this._data[prop]` only having a getter when being [set](https://github.com/canjs/can-define/blob/master/can-define.js#L280).

We want to revisit this change to ensure performance is not affected by this.

From @bmomberger-bitovi:
> we'll revisit it and get the right setter in that just end-runs around all the stuff the getter does.
(thus avoiding some slowdowns)

**Comment by justinbmeyer** [comment]
Fixing this now. It's an important performance feature.
