### ISSUE TITLE
'htmlbool' type is never false when set to a "false" or "0"

### ISSUE THREAD

**Issue by mjstahl** [canjs/can-define#196]
__How often can you reproduce it?__ 

- [X] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

Setting an 'htmlbool' attribute on a can-component is never set to `false` except in the case of the attribute not existing on the element.

For example:
`<foo-component expanded /> //-> expanded === '' === true` (per the documentation)
`<foo-component expanded="false" /> //-> expanded === "false" === true`

__Steps to reproduce:__

1. Create a component with an html attribute equal to false `<foo-component expanded="false" />`
2. On the above component, add a viewModel property `expanded` with a `type: 'htmlbool'`
3. Put something in your template that relies on that property being true/false, (i.e. `{{#if expanded}} .... {{/if}}`)

__Expected results:__
Per the documentation (https://canjs.com/doc/can-define.types.html), `htmlbool` should act like boolean ("false", "0", should be false) except for the fact that empty string is `true`.

Therefore `<foo-component expanded="false" />`, the viewModel property `expanded` should be falsey.

__Actual results:__

The viewModel property `expanded` (from the example above) is truthy.

__Analysis:__
Either the documentation is wrong, or we have a bug at:
https://github.com/canjs/can-define/blob/master/can-define.js#L862

The `typeof val === "string"` will short circuit when `expanded="false"`. 

I believe the `htmlbool` should be changed to:

```js
if (val === '') return true;
return define.types.boolean.apply(this, val);
``` 

__Environment:__

| Software                   | Version
| -------------------- | -------
| can-define version   | 1.0.17

**Comment by Macrofig** [comment]
The test cases for this, imo, are:

Truthy test cases:

```html
<foo-bar expanded>
<foo-bar expanded="">
<foo-bar expanded="heyo">
<foo-bar expanded="0">
<foo-bar expanded="1">
<foo-bar expanded="false">
<foo-bar expanded="true">
```

This means that, in the view model, setting `expanded` to `htmlbool` should convert any of the above values to truthy.

Falsey test case:
```
<foo-bar>
```

Based on the above, I believe that the documentation is wrong. The current coded behavior is correct (with one exception, see below).

I wonder, though, if these use cases shouldn't be using the `htmlbool` type:

```html
<foo-bar expanded="">
<foo-bar expanded="heyo">
<foo-bar expanded="0">
<foo-bar expanded="1">
<foo-bar expanded="false">
<foo-bar expanded="true">
```

Which, I suppose, means that Stache (I think it is Stache?) shouldn't be setting a value to `expanded` in the html/template. It should remove/add the property.
