### ISSUE TITLE
support rest/spread  and for/in loops

### ISSUE THREAD

**Issue by christopherjbaker** [canjs/can-define#199]
It would be very convenient if DefineMap instances could be used with the es6 rest and spread operators. These syntaxes only utilize enumerable properties.

```javascript
let { ...rest } = foo;
{ ...foo }
```

**Comment by justinbmeyer** [comment]
Can you add a description?

**Comment by justinbmeyer** [comment]
This is a duplicate of #34 I think.  I'll close that one.

**Comment by justinbmeyer** [comment]
I think `can-observe` has to be the fix for this, unless we bring in a proxy (or slow up can-define) to be less lazy.  Closing b/c I think we should focus on `can-observe`.
