### ISSUE TITLE
Simpler definition of get function

### ISSUE THREAD

**Issue by whitecolor** [canjs/can-define#2]
As poposal, treat:
```javascript
define: {
  visible: () => this.shown || this.animating
}
```
if it where:
```javascript
define: {
  visible: {
    get: () => this.shown || this.animating
   }
}
```

**Comment by justinbmeyer** [comment]
I keep going back and forth between get as the default meaning for a function and `type` functions:

```
define: {
  visible: types.boolean,
  age: types.number,
  name: types.string
}
```

The reason why `types` make sense to me is that you must write "something" for a property to be observable.  It makes the most sense that that "something" is the type.  So if you just wanted to define a bunch of properties you could do:

```
define: {
  prop1: types.any,
  prop2: types.any,
  prop3: types.any
}
```

I suppose the following would do the same:

```
define: {
  prop1: {},
  prop2: {},
  prop3: {}
}
```


For a getter ... I thought about allowing something like:

```
define: {
  "visible get": () => this.shown || this.animating
}
```

I'm not really settled yet.

**Comment by whitecolor** [comment]
May though not very consistent but led by convertion of usfullness:
if value is function (not constructor) it is treated as getter, if not as type.

**Comment by justinbmeyer** [comment]
@whitecolor are you currently using this?  I'm thinking that `get` is more useful for `can.Map`'s define, but `type` will be more useful for `can-define` because you have to define every property.

**Comment by whitecolor** [comment]
Isn't can define going to used for can.Map's define?

**Comment by justinbmeyer** [comment]
Perhaps we leave this open until someone has written an app with `can-define`.  Then we can check which option would reduce the overall code.

**Comment by whitecolor** [comment]
Ok, waiting for attr-less attributes much)

**Comment by justinbmeyer** [comment]
> Isn't can define going to used for can.Map's define?

I'm not sure.  Right now `can-define` uses `can.Map`'s define.  But the performance could probably be improved.  

My hope is that `can-observe` and `can-define` eventually totally replace `can.Map`.

**Comment by cherifGsoul** [comment]
@justinbmeyer dont you think this kind of abstraction can make confusion? I like seeing getter and setter in object definition they may help to control the behavior of writing/reading values

**Comment by whitecolor** [comment]
@justinbmeyer when canjs can be expected with attr-less?

**Comment by justinbmeyer** [comment]
@whitecolor it will be out with 3.0 in the next few months.  I went with using Type as the shortcut.  Defining types is more common than getters.
