### ISSUE TITLE
Should can-define support nullable and required properties?

### ISSUE THREAD

**Issue by bmomberger-bitovi** [canjs/can-define#20]
Currently in can-define, setting a `Type` attribute on a property ensures that after setting that property using `.attr()`, the property's value will be an instance of that `Type` class, even if the value passed to `.attr()`  is `null` or `undefined`.  The property's value starts as `undefined` if neither `Value` nor `value` is set, but once set, the only way to get a "null value" (`null` or `undefined`) for that property is to use `.removeAttr()`.

Likewise, setting `Value` or `value` enforces an initial value, but does not resist nor reset to default if `removeAttr()` is called for the property; the result is a value of `undefined`.

I think that it would be helpful to have slightly better type/value enforcement options.  Since sometimes we want to have a `Maybe<Map>` (as static-type functional programmers call it) where a property is assumed to have either an object of the parameter type or a null value, it may be sensible to allow for something like `nullable: true` as a define attribute.  This would prevent implicitly calling the constructor if the value is a null value.

Conversely, if users wanted to guarantee that a property always had a particular value, it would make sense to have a `required: true` attribute, which either disables `.removeAttr()` or follows it up with a call to the appropriate `Value` or `value` constructor.

Does this seem like a good idea?

**Comment by justinbmeyer** [comment]
@bmomberger-bitovi This is a bug then.  The following should pass:

```
Address  = DefineMap.extend({
  street: "string"
});

Person = DefineMap.extend({
  address: Address
});

p = new Person({address: {street: "Pinetree"}});
p.address = null;
QUnit.equal(p.address, null);
```

I know that the "date", "string" and "number" converters allow `undefined` and `null`.  


Btw, this repo is for the `define` plugin, are you looking for `can-map-define`?

**Comment by bmomberger-bitovi** [comment]
Yes, of course I'm looking for can-map-define.  Darn kids using the same name for everything.
![old-man-cloud](https://cloud.githubusercontent.com/assets/18686722/15954956/e7b3379e-2eaa-11e6-8a5b-9b81ef7eacdd.jpg)
