### ISSUE TITLE
type 'date' doesn't work on Safari 10

### ISSUE THREAD

**Issue by jeroencornelissen** [canjs/can-define#203]
__How often can you reproduce it?__

- [X] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
If you set type 'date' on a DefineMap property, the result is null.
I've tested on Safari 10.0.3 & 10.1.

```
var HomeViewModel = can.DefineMap.extend({
  page: 'string',
  startDate: 'date'
});
```

http://jsbin.com/jayosebojo/1/edit?html,css,js,output

__Expected results:__
The link should display something like:
_The date: Mon May 22 2017 15:30:00 GMT+0200 (CEST)_

__Actual results:__
_The date:_

__Environment:__

| Software                   | Version
| -------------------- | -------
| can-define version   | latest
| Browser                    | Safari 10.1 / Safari 10.0.3
| Operating system    | macOS 10.12.4

**Comment by justinbmeyer** [comment]
This is a bug with how `new Date()` works in safari.  It is unable to parse `'2017-05-22 15:30'`.  You'll need to use a string format that works everywhere.  For example:

```js
new Date("Mon May 22 2017 15:30:00 GMT-0500 (CDT)")
```

Fixing date parsing is beyond what CanJS should do.  However, it's easy to create a type converter that uses moment or something like:

```js
var momentDate = function(rawDate){
  return MOMENT_TO_DATE(rawDate);
}

DefineMap.extend({
  myDate: {type: momentDate}
})
```

**Comment by jeroencornelissen** [comment]
Yeah, figured out Safari needs a complete ISO8601 date string.
I'm currently using [date-fns parse function](https://date-fns.org/docs/parse) to parse my dates correctly cross browser.
