### ISSUE TITLE
avoid removeSpecialKeys

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-define#208]
so `setProps` calls `assign` and then `removeSpecialKeys` which is going to loop over all properties in props and then delete values.  This is probably overly expensive.

Instead of doing this, can we just check for special keys in the `this.each` and `for/in` loop?  Ideally, we'd do this with an `O(1)` lookup

```
if( specialKey[prop] ) {
  return  // or break
}
```

**Comment by bmomberger-bitovi** [comment]
All references to removeSpecialKeys (and the helper itself) were removed in commit 66886b07153c9bc6fd5e149c47e0ced6009f9692
