### ISSUE TITLE
Parameter CleanUp

### ISSUE THREAD

**Issue by BigAB** [canjs/can-define#21]
I have always considered the arguments passed in to Map.extend params confusing and unintuitive.

`can.DefineMap.extend( instancePropsMethods )` -> one argument extends the prototype
`can.DefineMap.extend( static, instancePropsMethods )` -> if I add a second argument, I have to move the options to the second position because now the first position extends the constructors 'static' methods
`can.DefineMap.extend(  'name', static, instancePropsMethods )` -> to add a name I have to shift it all down because the first argument is now a string for name.

I can't think other examples in other popular libraries that make you shift around your arguments depending on how many you provide.

With this as an opportunity to break from the legacy confusion, would you consider a signature like:

`can.DefineMap.extend(prototype, [,static]  [, options:{ name } ])`
_where options would be an optional argument which is an object with an optional name property_

**Comment by justinbmeyer** [comment]
This belongs in can-construct.
