### ISSUE TITLE
assign() from a DefineMap copies over .each() and .toObject()

### ISSUE THREAD

**Issue by bmomberger-bitovi** [canjs/can-define#210]
https://jsbin.com/jeyukutuyi/1/edit?html,js,console,output

__Description:__

The assign() function internally uses a for...in loop to iterate over objects, which pulls in all enumerable keys all the way up the prototype chain.  Because DefineMaps use `=` to set .each() and .toObject() on the prototype, these functions are included when setting to an assignment.  By contrast, all other prototype functions are set using `Object.defineProperty()` and setting the `enumerable` property to false.  These should also be defined the same way to avoid copying them incorrectly to other objects.

However there is a complicating factor.  `can-util/js/is-plain-object` looks at the prototype chain for enumerable non-own properties to figure out if an object is a plain object.  Removing these final two properties from the DefineMap prototype incorrectly reports DefineMaps as being plain objects.  This would also have to be addressed by any fix.

__Steps to reproduce:__

1. Create a plain object and a DefineMap instance.
2. use `can-util/js/assign/assign` to assign the DefineMap to the plain object

__Expected results:__

1. set properties on the DefineMap are the only properties to be copied to the plain object.

__Actual results:__

1. set properties and the functions `each` and `toObject` are copied.

__Environment:__

| Software                   | Version
| -------------------- | -------
| can-define version   | 1.0.26
| Browser                    | Chrome tested (not browser-related)
| Operating system    | MacOS Sierra 12.5

**Comment by justinbmeyer** [comment]
So isPlainObject probably needs to be a. It smarter

**Comment by bmomberger-bitovi** [comment]
Closed via #165
