### ISSUE TITLE
Extended DefineMap properties with short-hand Type DefineMap does not allow properties to be set

### ISSUE THREAD

**Issue by roemhildtg** [canjs/can-define#221]
__How often can you reproduce it?__ 

- [x] Always - v1.2.x
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

```javascript

import DefineMap from 'can-define/map/map';

var Child = DefineMap.extend('child', {
  other: DefineMap
});

var c = new Child();
c.other = {
  prop: 'hello'
}; //error Cannot add property other, object is not extensible

```

__Steps to reproduce:__

1. Include a JS Bin (or equivalent) link if possible
2. Detail the exact steps taken to produce the problem
3. Include a gif if possible; you can use LICEcap to make a gif: http://www.cockos.com/licecap/

__Expected results:__

Shorthand prop: DefineMap should work.

__Actual results:__

Throws error Cannot add property other, object is not extensible

__Environment:__

| Software                   | Version
| -------------------- | -------
| can-define version   |  1.2.x
| Browser                    | Chrome 59.0.3071.109 (Official Build) (64-bit)
| Operating system    | Windows x64

**Comment by justinbmeyer** [comment]
So the problem here seems to be that `DefineMap` doesn't pass `canReflect.isConstructorLike`.

We can add the `can.new` symbol.

But I think another way might be to check the `.prototype.proto` is not null?

**Comment by justinbmeyer** [comment]
There's a few options to fix this:

## Test the proto chain

Something like this would work:

```js
nomalFunc = function(){};
SomeConstructor = function(){

}
SomeConstructor.prototype = Object.create( AnythingOtherThanNull);


Object.getPrototypeOf( Object.getPrototypeOf( nomalFunc.prototype ) ) //-> null
Object.getPrototypeOf( Object.getPrototypeOf( nomalFunc.prototype ) ) //-> AnythingOtherThanNull
```

## Test for non enumerable properties on the prototype chain

```js
nomalFunc = function(){};
SomeConstructor = function(){

}
SomeConstructor.prototype[symbol] = function(){ ... }
assignNonEnumerable( SomeConstructor.prototype, {anything: function(){}})


Object.getPrototypeOf( Object.getPrototypeOf( nomalFunc.prototype ) ) //-> null
Object.getPrototypeOf( Object.getPrototypeOf( nomalFunc.prototype ) ) //-> AnythingOtherThanNull
```

I think this is the better approach:

![can-define_tests](https://user-images.githubusercontent.com/78602/27499268-a5d887e0-5828-11e7-90f0-942eff37d34b.png)

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-reflect #18](https://github.com/canjs/can-reflect/issues/18) via [**ZenHub**](https://www.zenhub.com/)
