### ISSUE TITLE
date types are not serialized correctly

### ISSUE THREAD

**Issue by roemhildtg** [canjs/can-define#237]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

Calling serialize on a map with the `type:'date'` does not serialize the date correctly. Instead an empty object is returned.

__Steps to reproduce:__

```javascript
  steal.import('can-define/map/map').then(function(module){
  const VM = module.extend({
    show: {
      type: 'date'
    },
  });

  const m = new VM({
    show: new Date()
  })

  console.log(m.serialize());
  });
```

__Expected results:__

The map.serialize method should return date objects, not empty objects. 

__Actual results:__

An empty object is returned for date values.

__Environment:__

| Software                   | Version
| -------------------- | -------
| can-define version   | 1.3.x (all 1.3)
| Browser                    | Chrome 59
| Operating system    | Windows 7

**Comment by Sinjhin** [comment]
This should be fixed with https://github.com/canjs/can-reflect/pull/37
