### ISSUE TITLE
Setting a DefineList Type property on a map with set method doesn't work

### ISSUE THREAD

**Issue by roemhildtg** [canjs/can-define#243]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

__Steps to reproduce:__

http://jsbin.com/lewozogego/edit?js,console

1. Create define map with `type: DefineList`
2. Call `set` on the map with the property name set to a different array.

__Expected results:__

Property should be set to new value

__Actual results:__

The property is not updated.

__Environment:__

| Software                   | Version
| -------------------- | -------
| can-define version   | 1.3.3
| Browser                    |  Chrome
| Operating system    |  Windows 7

**Comment by phillipskevin** [comment]
using `.set(..., true)` does set the new array, so we may just need to determine if this is the correct behavior and clarify in the docs.

**Comment by phillipskevin** [comment]
related conversation: https://gitter.im/canjs/canjs?at=5984beba4bcd78af561462c1

**Comment by justinbmeyer** [comment]
This is the expected behavior.  Use replace or `.set([], true)`

**Comment by justinbmeyer** [comment]
To give a little more context:

`map.set({})` doesn't remove properties, this is why `list.set([])` doesn't.

**Comment by justinbmeyer** [comment]
odd, this seemed to become a problem in 3.9.  Re-opening.

**Comment by roemhildtg** [comment]
Yeah, its a bit confusing at the moment as to what I should expect when calling `set`. 

Should this merge behavior apply to nested properties? (currently it looks like it does not).

http://jsbin.com/gecohikano/edit?js,console

```javascript
const obj = new MyConstruct({
  list: [['test_array'], {object: 'data'}, {object: 'data'}, {object: 'data'}]
});

obj.set({
  list: [[], {other: 'prop'}]
});
```

**Comment by phillipskevin** [comment]
We're going to handle this with https://github.com/canjs/can-define/issues/245, which will provide more explicit, well-documented methods to use instead of `.set`.
