### ISSUE TITLE
Proposal: can-reset

### ISSUE THREAD

**Issue by cherifGsoul** [canjs/can-define#253]
After thinking about this issue https://github.com/canjs/can-define/issues/170 and discussion with @justinbmeyer we conclude that is not possible to use try-catch for performance reasons.

I propose to have can-reset module to reset CanJS to the initial state, the API can have:
```js
canReset.reset() //to dispatch events and invokes bounded event handlers
canReset.onReset(handlers) //to bind event handlers when state is reseted
```

**Comment by phillipskevin** [comment]
Issue moved to [canjs/canjs #3502](https://github.com/canjs/canjs/issues/3502) via [**ZenHub**](https://www.zenhub.com/)
