### ISSUE TITLE
Extract out replaceWith

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-define#260]
[replaceWith](https://github.com/canjs/can-define/blob/af174485b386b70382d35ed4b768333022e89628/can-define.js#L742-L765) is a very useful utility function that should be extracted out to its own module so that it can be used other places.

**Comment by justinbmeyer** [comment]
- write a short blog

**Comment by bmomberger-bitovi** [comment]
I recommend we punt on this until we are ready to start doing scoped packages.

**Comment by justinbmeyer** [comment]
This is something that a few places need. And the can-observe will need it cc @bgando.

Doing it now is still valuable and one more package isn’t going to create additional problems. I’d like to do it now.

**Comment by phillipskevin** [comment]
I'm planning to work on this one tomorrow.

**Comment by phillipskevin** [comment]
Going to go with `can-define-lazy-value` for the name.

**Comment by phillipskevin** [comment]
This has been published.
