### ISSUE TITLE
Proposal: Lifecycle hooks

### ISSUE THREAD

**Issue by andrejewski** [canjs/can-define#288]
As someone writing third-party extensions to DefineMaps, I want to be able to bind to things and safely teardown down those bindings later. 

Right now DefineMaps don't offer this. Instead you use `inserted` and `removed` on your can.Component to setup your bindings in your ViewModel. This is okay, but has problems:

- There is no convention. You can bind to inserted/removed in the ViewModel with `events` and then call the `this.viewModel.inserted()` or any other method.
- This doesn't scale when there isn't an exact one-to-one mapping between Component and ViewModel. In the case of a VM that has a child list of DefineMaps, I have to write setup and teardown boilerplate to manage those children which should leverage my extension (and with dynamic children, yuck).

As a third-party developer, I can't do much to prevent this cruft and I'm led to making a bad design of my extension with some ad hoc behavior for users to teardown my bindings when they think is appropriate. But this should not be their concern.

The solution is lifecycle hooks; but not in the Component inserted/removed/isInDom sense. What I really want is the following methods:

- `onBound()` for when I can start binding using `.on()`
- `onUnbound()` for when I can stop binding using `.off()`
- `isBound()` for checking if my extension should set up bindings dynamically if it's already bound

These methods are DOM/Component independent. While it may make sense for the Component to call these hooks on the ViewModel when the Component is inserted or removed, these hooks can be used in other scenarios.

This addresses the above concerns:

- We don't need a convention, we have an API.
- Now we can have our DefineMap, when it has children, also call their `onBound()` methods. Eliminating boilerplate that we would have to write now.

For example, I have this library for type checking [trent](https://github.com/andrejewski/trent) and I want to write a DefineMap extension where every time any property changes I can run a type check. This is just an example, and I'd probably only want to do these checks in development.

I'd write with these new lifecycle hooks:

```js
// can-define-trent.js

import {createSpec} from 'trent'

export default function (specBuilder) {
  const spec = createSpec(specBuilder)
  return function specMap (mapClass) {
    return mapClass.extend({
      onBound () {
        this._super(...arguments)
        this._specBinding = () => {
          const errors = spec.getErrors(this.serialize())
          errors.forEach(error => console.error(error))
        }
        this.on('*', this._specBinding)
      },
      offBound () {
        this._super(...arguments)
        this.off('*', this._specBinding)
      }
    })
  }
}
```

The big takeaway here is I can write binding extensions for plain DefineMaps and don't need to incorporate knowledge of Component (or something else potentially) in order to be memory-safe.

Note: I really don't care about the naming or even having the hooks directly in the DefineMap's definition; these could be somewhere else but need to be available for third-party extensions.

**Comment by justinbmeyer** [comment]
I think this is a good idea and suggest `connected` instead of bound like Custom Elements.  

```
DefineMap.extend({
  connectedCallback() {
    this.on("todosPromise",(todosPromise) => {
      todosPromise.then( (todos) => { this.todosList =  todos; }
    })
  }
  disconnectedCallback(){ 
    this.off();
  }
})
```

**Comment by justinbmeyer** [comment]
I've been thinking about `connectedCallback` a bit.  I'm wondering if it should be used for more than signaling that a VM is connected to a custom element.  Ideally it would signal that anything is "connected" (for example bound) to the instance.  This seems especially important because VM bindings start listening to changes in the VM immediately, before `connectedCallback` would be called due to an element being inserted in the page.  I feel like we'd want `connectedCallback` to fire immediately, allowing it to manage the state.  



This is similar to the original proposal. But there seems to be a problem.  Making `connectedCallback` get called whenever something is first bound to an instance is easy.  However, making `disconenctedCallback` work is much trickier, especially since `connectedCallback` sets up bindings, including bindings on itself.  We'd have to know when bindings except for the `connectedCallback` bindings (and the  `connectedCallback` bindings might change, or even create cycles).

Consider:

```js
class Foo extends observe.Object {
  constructor(props){
    super(props)
    this.numberOfTodos = this.todos.length;
    this.updateTodosLength = this.updateTodosLength.bind(this)
  }
  connectedCallback(){
    
    this.on("todos", this.todosUpdated.bind(this) )
  },
  todosUpdated: function(todos. oldTodos){
    oldTodos.off("length", updateTodosLength );
    todos.on("length", updateTodosLength );
  },
  updateTodosLength: function(length){
    this.numberOfTodos = length;
  }
}
```

How could we know that the bindings created and updated via the `connectedCallback` call should NOT be included in count of "external" bindings?

> One possible answer is to use special functions for this purpose.  `this.listensTo()` or `this.makeHandler("updateTodosLength")` ... for example. 
 We could see these handlers and ignore them.  This feels icky though.
> Streams I feel like can solve this.  We'd allow a user to create some source streams, mark those as being "ignored" and then everything must be derived from them.  

Currently I feel like there are 3 possibilities:

1.  Come up with an elegant solution for the above problem.
2. Run `connectedCallback` immediately upon the constructor creation, and `disconnectedCallback` when the element is removed from the page immediately ("beforeremoved" called via nodelist).
3.  Run `connectedCallback` on `inserted` and `disconnectedCallback` when the element is removed from the page asynchronously ("removed")

**Comment by andrejewski** [comment]
One thing we could consider is an isolated method that encapsulates both setup and teardown. For example (naming non-important):

```js
// can-define-trent-2.js

import {createSpec} from 'trent'

export default function (specBuilder, viewModel) {
  const spec = createSpec(specBuilder)
  viewModel.subscribe(() => {
    const specBinding = () => {
      const errors = spec.getErrors(viewModel.serialize())
      errors.forEach(error => console.error(error))
    }
    viewModel.on('*', specBinding)
    return () => viewModel.off('*', specBinding)
  })
}
```

This above is nice because:

- Not 2 special lifecycle hooks, one method.
- No inheritance or need to remember to call `super` and store the function on the map (as `_specBinding` in the original example).
- Easy to have multiple subscriptions, all of which can leverage `on`, `listenTo`, etc
- The logic is all in one place.

For the cycle problem, we could make the semantics of `subscribe` conform to the rule that subscriptions should be idempotent. Meaning, we *could* at any time teardown the subscription even if it is not the end of the VM's lifetime and re-bind using the setup call again. This is to say that if we find an appropriate time to purge a given VM we can unbind the subscriptions and if there are no binding after then the view model is properly torn down; otherwise re-bind the subscriptions. The pitfalls with this:

- The complexity/performance cost of tearing down and then re-establishing bindings if we guess wrong on an appropriate time to teardown. I assume we'd usually guess right, and if we didn't we should probably warn from the can-component side that we could not successfully clean everything up.
- Finding an appropriate time to attempt to teardown. We'd need some low-level `attemptTeardown` method that would be called by can-component or whatever manages the viewModel. For can-component the right time to try is after `removed` because we want those bindings undone before we try with the subscriptions.

One very cool advantage of this approach is that we can verify the "idempotency" of subscriptions in development mode by checking (in a one-off test) binding counts before and after setup/teardown and warn about erroneous bindings.

**Comment by matthewp** [comment]
> This seems especially important because VM bindings start listening to changes in the VM immediately, before connectedCallback would be called due to an element being inserted in the page. I feel like we'd want connectedCallback to fire immediately, allowing it to manage the state.

I'm not sure I follow this. Is this something to do with can-component?  I especially don't understand "VM bindings start listening to changes in the VM immediately", that doesn't sound right to me... VM bindings start when something calls `canReflect.onKeyValue(key)`, right?

**Comment by justinbmeyer** [comment]
@matthewp 

If you have `<my-component foo:bind="bar"/>`, `can-component` does the following:

1. `new VM({foo: barValue})`
2. `vm.on("foo", updateBar)` `scope.on("bar", updateVMFoo)`

Bindings are setup before an `inserted` event fires.

**Comment by matthewp** [comment]
Ok, so this is an issue with can-component integration. We should keep this in mind so that we don't bias the design of these hooks towards can-component needs; can-element does *not* set up bindings before the element is inserted.

**Comment by matthewp** [comment]
To clarify the above, remember that custom elements must be *much* more flexible than can-components. can-components are created in a controlled environment. The framework handles creating them and destroying them.

Custom elements like those that can-element creates can be used in many different ways. So having them create side effects (and memory leaks) upon instantiation because that would require the user to destroy them manually.

Consider as an example that you author a JSX/hyperscript library and you want to accept custom element constructor functions instead of string tag names. In order to get the tag name you actually have to create an instance of the element like below:

```js
function myHyperscriptLibrary(ctrOrTag) {
  var tagName;
  if(typeof ctrOrTag === "string") {
    tagName = ctrOrTag;
  } else if(ctrOrtag instanceof HTMLElement) {
    tagName = new ctrOrTag().localName;
  }

  ...
}
```

**Comment by justinbmeyer** [comment]
@matthewp can-element does not set up bindings before the element is inserted.

But it could when the constructor is run.

**Comment by matthewp** [comment]
That would have the problem I described above ^^.

**Comment by justinbmeyer** [comment]
@andrejewski I like that sort of setup / teardown.  Though, I think the default `teardown` should be `this.stopListening(); this.off()` (`this.off()` might not be needed).


But I'm not quite getting the rest of what you are saying. On idempotency, this was what I meant by:

> How could we know that the bindings created and updated via the connectedCallback call should NOT be included in count of "external" bindings?

Though I'm not sure I understand if you've got a suggestion for how to do that?

I'll elaborate on `this.listenTo()`, as it's probably the closest to working, but doesn't solve the cycle problem.

First, bindings can't truly be idempotent as you have to register an event handler on something.  However, we can make some event bindings idempotent with respect to "is something __outside__ connected".

My proposal:

 - `connectedCallback` as the callback when something __outside__ binds to a viewModel, it returns a __teardown__ function called when the last "outside" binding is removed.
- `listenTo([bindTarget=this], keyName, handler)` is used to setup __inside__ bindings.

```
class ViewModel extends observe.Object {
  constructor(props){
    super(props)
    this.numberOfTodos = this.todos.length;
  }
  connectedCallback(){
    var updateTodosLength = this.updateTodosLength.bind(this)
    this.listenTo("todos", (newTodos, oldTodos) => {
      this.stopListening( oldTodos, "length", updateTodosLength );
      this.listenTo( todos, "length", updateTodosLength );
    });
    return () => { this.stopListening() }
  },
  updateTodosLength: function(length){
    this.numberOfTodos = length;
  }
}
```

With this setup, if someone bound from the __outside__ to an instance of this viewModel like:

```js
var vm = new VM();
vm.on("numberOfTodos", handler);
```

The `connectedCallback` would be run.  


`this.listenTo()` would setup bindings in such a way that they wouldn't be considered __outside__ bindings when done on yourself.  

For example, the following could be stored in such a way that the number of __outside__ bindings would be:

```
this.listenTo("todos", (newTodos, oldTodos) => { });
```

We could easily see that if someone unbound the outside binding:

```js
vm.off("numberOfTodos", handler);
```

The only handlers remaining would be __inside__ handlers.  

However, this does not seem to solve the `cycle` problem (without implementing something like a GC algorithm).

For example:

```
class A {
  connectedCallback() {
    this.listensTo(b, "value", () => {
      this.bChangeCount++;
    })
  }
}
class B {
  connectedCallback() {
    this.listensTo(a, "value", () => {
      this.aChangeCount++;
    })
  }
}

a = new A()
a.value = 0;
b = new B();
b.value = 0;

a.b = b;
b.a = a;

a.on("bChangeCount", handler);
```

When `a.on("bChangeCount", handler);` happens, we'd want to run `a.connectedCallback()` and the binding that creates on `b` should run its  `b.connectedCallback()`.

When `a.off("bChangeCount", handler);` is run, how could we know that the remaining bindings between `a` and `b` are completely `listenTo` bindings and tear them all down?

**Comment by justinbmeyer** [comment]
The following might be how we can solve the cycle issue.

First, some shorthand:

```
// means a listens to b's value change in a's connectedCallback
a.listensTo(b,"bValue") 
```

I'll show this handler like:

```
b { FOR:a:bValue }
```

A normal handler like `b.on("bValue")` will look like:

```
b { FOR:a:bValue OUT:bValue }
```

## Example 

```
a.listensTo(b,"bValue")
b.listensTo(a,"aValue")
c.listensTo(a,"aValue")

// STEP A
a.on("aValue", h1);

a { OUT:aValue FOR:b:aValue } //1. CONNECTED
b { FOR:a:bValue }            //2. CONNECTED
c {}

// STEP B
c.on("cValue",h2)

a { OUT:aValue FOR:b:aValue FOR:c:aValue }
b { FOR:a:bValue }
c { OUT:cValue }

// STEP C
a.off("aValue",h1)

a { FOR:b:aValue FOR:c:aValue }
b { FOR:a:bValue }
c { OUT:cValue }
/*
1. OUT:aValue is removed
2. FOR:a's are collected
   - FOR:a:bValue
3. FOR:b's are collected
   - FOR:b:aValue
4. These are hypothetically removed, leaving
   a { FOR:c:aValue }
   So no disconnects.
*/


// STEP D
c.off("cValue",h2)

a { } //3. DISCONNECTED
b { } //2. DISCONNECTED
c { } //1. DISCONNECTED
/*
1. OUT:cValue is removed
2. FOR:c's are collected
   - FOR:c:aValue on a
3. FOR:a's are collected
   - FOR:a:bValue on b
4. FOR:b's are collected
   - FOR:b:aValue on a
4. These are hypothetically removed, leaving 
   nothing on c, b, a
   so disconnect.
*/
```

**Comment by justinbmeyer** [comment]
## Implementation ideas

Terminology:

- bindSource - the `this` of `this.listenTo( bindTarget, event, handler)`
- bindTarget - this `bindTarget` of `this.listenTo( bindTarget, event, handler)`

`bindSource` is what is doing the binding.  `bindTarget` is what we are listening to. 

### WeakMaps 

```
var mapToBindings = new KeyTree([WeakMap, Map, Object, Array])
this.listenTo = function(bindTarget, key, handler){ 
  mapToBindings.add([bindTarget, this, key, handler])
  // existing code
}
```

With something like the above, we could "collect" bindings pretty easily:

```js
// this is called after an OUT binding has been removed
checkDisconnect() {
  var totalHandlers = this.handlers.get([]).length;
  var handlersRemovedByADisconnect = getBindTotalHandlers( this, this )
  if( handlersRemovedByADisconnect === totalHandlers) this.disconnect()
},
getBindTotalHandlers = function(bindTarget, currentTarget){
  var bindSources = mapToBindings.getNode([bindTarget]);
  var count = 0;
  for(let [bindSource, keyHandlers] of bindSources){
    if(bindSource === currentTarget) {
      count += countOfHandlersIn(keyHandlers)
    } else {
      count += getBindTotalHandlers(bindSource, currentTarget)
    }
  }
  return count;
}
```

A likely performance issue with something like this is that a big teardown would be similar to `O( (n^2 - n)/2 )` problem (handshake).  We'd explore the whole graph, then disconnect the first map, which would then remove handlers from other elements, and repeat.  A better version would be able to notice disconnects as it goes and call them all w/o further `checkDisconnect` calls.

The other problem with this is that this weakmap would be stateful.

### Store the "bindTarget" as metadata.

Another option would be to make `onKeyValue()` take and store an additional `bindTarget` like:

```js
canReflect.onKeyValue( person, "first", "notify", viewModel)
```

This binding would be registered to `viewModel` like `viewModel.listenTo` does now.  However, we'd also be able to loop through `person`'s bindSources to keep recursing.

Problems:

- Another argument to `onKeyValue`  ... gross!
- The KeyTree structures would change to include metadata, and they are currently optimized to work with `queues.enqueueByQueue`.

**Comment by justinbmeyer** [comment]
Closing b/c we added `connectedCallback` in Component and https://github.com/canjs/can-define/issues/288 can be used to discuss the larger problem of making this work generically through binding.
