### ISSUE TITLE
deepAssign does not support updating arrays using objects with numeric keys

### ISSUE THREAD

**Issue by RyanMilligan** [canjs/can-define#308]
__How often can you reproduce it?__ 

- [ x ] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__ deepAssign() does not support updating specific items in arrays by passing objects with an index of, for example, 1. Instead, it ignores the keys in the source object and updates the first N items in the array.

1. JSBin: https://jsbin.com/suyowov/edit?js,console,output
2. Open the console and run the script
3. The third object output should show that "second" has changed to 2, but instead the 1 from the previous output has changed to 2

__Actual results:__ Only the first item in the array can be edited in this way

__Environment:__

| Software                   | Version
| -------------------- | -------
| can-define version   | 1.5.4
| Browser                    |  Chrome Update 63
| Operating system    |  Windows 10 # #

**Comment by RyanMilligan** [comment]
A proposed solution can be found in [,](https://github.com/RyanMilligan/can-reflect/pull/1) but I logged it here at the request of @phillipskevin.

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-reflect #99](https://github.com/canjs/can-reflect/issues/99) via [**ZenHub**](https://www.zenhub.com/)

**Comment by justinbmeyer** [comment]
thanks for reporting, moving to can-reflect.

**Comment by justinbmeyer** [comment]
I'm not sure the proposed solution is the right one.  What should `toArray({0: "a"})` return?
