### ISSUE TITLE
2 properties that are bound are out of sync

### ISSUE THREAD

**Issue by PieterSwitten** [canjs/can-define#321]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
See the jsbin and the gif to see the problem.
2 properties are bound to each other, when I change the property in my parent it changes also in my child component. 
But when I change the property back to the original value inside the setter of my child property it is not changed back in the parent component. 

At this point the 2 properties are out of sync.

__Steps to reproduce:__

https://jsbin.com/zacadiciru/63/edit?html,js,console

![problem](https://user-images.githubusercontent.com/10957732/36845792-5ec22f5a-1d58-11e8-8e79-93426e826f9f.gif)

__Expected results:__
```
console.log(parent.childVisibility) // --> false
console.log(child.visible) // --> false
```

__Actual results:__
```
console.log(parent.childVisibility) // --> true
console.log(child.visible) // --> false
```

__Environment:__

| Software                   | Version
| -------------------- | -------
| can-define version   | 2.0.3
| Browser                    | Chrome
| Operating system    | macOS High Siera

**Comment by justinbmeyer** [comment]
I’m not sure this is why (away from computer) but bindings only allow one parent<->child change per batch. So if you change a parent value, and that changes a child, the child will not update the parent. This is to avoid cycles. Kevin has talked about removing this protection.

**Comment by justinbmeyer** [comment]
Btw, thanks for creating such a nice issue.

We could create a special syntax for now to allow essentially infinite cycles.  Would you be interested in trying this out?

I would like to come up with a better name, but something like

```
<child-tag visible:bind:cycle="childVisibility" />
```

Where `cycle` would allow looping.  Maybe `sticky` would work too.  cc @phillipskevin 

Just to make sure this fixes your problem, could you try commenting out:

https://github.com/canjs/can-stache-bindings/blob/908c2ae63bfa191f1d979b14e948b0d7f1d3a70a/can-stache-bindings.js#L663

```
// bindingsSemaphore[attrName] = (bindingsSemaphore[attrName] || 0) + 1;
```

And https://github.com/canjs/can-stache-bindings/blob/908c2ae63bfa191f1d979b14e948b0d7f1d3a70a/can-stache-bindings.js#L668

```js
--bindingsSemaphore[attrName];
```

And https://github.com/canjs/can-stache-bindings/blob/908c2ae63bfa191f1d979b14e948b0d7f1d3a70a/can-stache-bindings.js#L720:

```js
bindingsSemaphore[attrName] = (bindingsSemaphore[attrName] || 0) + 1;
```

And https://github.com/canjs/can-stache-bindings/blob/908c2ae63bfa191f1d979b14e948b0d7f1d3a70a/can-stache-bindings.js#L726

```js
--bindingsSemaphore[attrName];
```

**Comment by justinbmeyer** [comment]
moving to can-stache-bindings as this is an issue there.

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-stache-bindings #443](https://github.com/canjs/can-stache-bindings/issues/443) via [**ZenHub**](https://www.zenhub.com/)
