### ISSUE TITLE
DefineMap and DefineList set(props [, removeProps]) deprecation cleanup

### ISSUE THREAD

**Issue by James0x57** [canjs/can-define#322]
The deprecation warning here:
https://canjs.com/doc/can-define/map/map.prototype.set.html
and here:
https://canjs.com/doc/can-define/list/list.prototype.set.html

can be cleaned up and removed for 4.0 along with the `set(props [, removeProps])` signature that the deprecation warning is related to.

**Comment by justinbmeyer** [comment]
We should remove the signature too:

![image](https://user-images.githubusercontent.com/78602/40868994-6045644a-65d9-11e8-92c8-46af20a5f6b0.png)

**Comment by matthewp** [comment]
Add a warning for using this as part of removing the docs.

**Comment by matthewp** [comment]
Reverted as @chasenlehara argued the deprecation notice in the doc is helpful and should be released in the next can-define major.
