### ISSUE TITLE
DefineMap type method call with wrong this context

### ISSUE THREAD

**Issue by Mamuuut** [canjs/can-define#349]
__How often can you reproduce it?__

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Steps to reproduce:__

https://codepen.io/Mamuuut/pen/gKJvEL
1. open the browser dev tools
2. It should break inside the `propA` type method with this being `window` instead of `oMap`.

I would expect this to be `oMap` instead of `window` or `undefined`.

**Comment by justinbmeyer** [comment]
Thanks for reporting. Is this a regression? I could see the new type system as causing this. We should be able to fix today.

**Comment by justinbmeyer** [comment]
Will have to wait until tomorrow

**Comment by Mamuuut** [comment]
Hi,
thanks for the super fast response.
I had the problem in v3 while migrating CanMap to DefineMap and checked v4 where the problem still exists.
It could be considered a regression compared to CanMap but it's a completely different Class…

**Comment by justinbmeyer** [comment]
@Mamuuut just in case you weren't aware, `can-map` is still supported so you don't have to migrate all your code to define map to run on v4.

**Comment by justinbmeyer** [comment]
ah, seems to be a problem when there is a default

**Comment by justinbmeyer** [comment]
fixed in 2.5.0: https://github.com/canjs/can-define/releases/tag/v2.5.0
