### ISSUE TITLE
Support deleting custom keys

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-define#351]
This demo should be possible to make work, but it doesn't: https://codepen.io/justinbmeyer/pen/QxXpGR?editors=1010

We need some sort of `deleteKey()` working.  It should remove keys from instance definitions: https://github.com/canjs/can-define/blob/master/define-helpers/define-helpers.js#L25

If a defined key is attempted to be deleted, we should set to `undefined` as works now, but maybe warn?

**Comment by chasenlehara** [comment]
I think this has been fixed in can-define@2.5
