### ISSUE TITLE
DefineMap .serialize() does not bind to a DefineList's length property

### ISSUE THREAD

**Issue by matthewp** [canjs/can-define#372]
This should demonstrate the bug: https://jsbin.com/zowesaf/edit?html,js,console

I expect an event when the DefineList grows. I don't see one.

Stepping through the code, I think the problem [is here](https://github.com/canjs/can-define/blob/2a776fbb509bbf9f989725cd6a82f58b6e11fdbe/list/list.js#L1683-L1697). Is this using a non-observed property on purpose?

**Comment by justinbmeyer** [comment]
The commit: https://github.com/canjs/can-define/commit/f385cc6e58188f676ea002a659d41c8ac6e52706

@bmomberger-bitovi any thoughts?

**Comment by matthewp** [comment]
Pretty sure it was not intentional. Fix incoming.

**Comment by matthewp** [comment]
PR: https://github.com/canjs/can-define/pull/373
