### ISSUE TITLE
log, setup, init are enumerable in Safari

### ISSUE THREAD

**Issue by matthewp** [canjs/can-define#389]
This change added a test for object enumerability: https://github.com/canjs/can-define/pull/385

This fails in Safari. The reason seems to be that in Safari if a property is enumerable on a parent proto but not on a child, it *will* count that property. With Chrome it doesn't count it if the child has the property as non-enumerable. In other words, Safari is more greedy about enumerability.

**Comment by thomaswilburn** [comment]
There's a change in the IE11 pull request that will check for this and short-circuit the test (it happens in IE as well): https://github.com/canjs/can-define/pull/386/commits/292f368fec42995efaa9d1c43e87aa1b96e86f83

**Comment by matthewp** [comment]
Hopefully my changes will remove the need for changing the test.
