### ISSUE TITLE
can-define/map does not call instance level setup

### ISSUE THREAD

**Issue by m-mujica** [canjs/can-define#395]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

`setup` functions defined in the instance properties of `DefineMap` are not called.

__Steps to reproduce:__

https://codepen.io/anon/pen/VEwgPa?editors=1111

```js
import { DefineMap } from "//unpkg.com/can@5/core.mjs";
var Type = DefineMap.extend({}, {
	setup(attrs) {
		console.log('ATTRS: ', attrs); // <- THIS SHOULD BE CALLED
		return DefineMap.prototype.setup.apply(this, arguments);
	}
});
var map = new Type({ foo: 'bar' });
```

**Comment by justinbmeyer** [comment]
So the problem here is that `DefineMap.prototype.setup` will default to NOT sealing the instance.  This might not be what you want.  To seal, you'd have to do:

```
var Type = DefineMap.extend({}, {
	setup(props) {
		console.log('ATTRS: ', props); // <- THIS SHOULD BE CALLED
		return DefineMap.prototype.setup.call(this, props, true);
	}
});
```
