### ISSUE TITLE
Getters do not bind on non-defined nested properties

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-define#413]
In the code below, setting `foo.bar` (like `this.updateDeep({ foo: { bar: "this is foo.bar" } });`) doesn't update `fooBar`:

```
    foo: {
      Type: DefineMap,
      Default: DefineMap
    },
    
    get fooBar() {
      return this.foo && this.foo.bar;
    }
```

...but if you default `foo.bar` to `undefined` it works:

```
    foo: {
      Type: DefineMap,
      default: () => ({ bar: undefined })
    },
    
    get fooBar() {
      return this.foo && this.foo.bar;
    }
```

Here is a codepen: https://codepen.io/kphillips86/pen/PxrRNX?editors=0010

**Comment by phillipskevin** [comment]
cc @justinbmeyer this seems confusing, but is it intended?

**Comment by justinbmeyer** [comment]
I don’t think so. Why doesn’t this work?

**Comment by phillipskevin** [comment]
It doesn't work because there is no getter set up for `bar` on the default `foo` object. This also didn't work in 3.0.

cc @m-mujica.

**Comment by justinbmeyer** [comment]
oh, yeah, this makes sense then ... this isn't a bug.  I bet this would work:

```
    foo: {
      Type: DefineMap,
      Default: DefineMap
    },
    
    get fooBar() {
      return this.foo && this.foo.get("bar");
    }
```

`can-observe` "fixes" this.

**Comment by justinbmeyer** [comment]
Also so would:

```js
get fooBar(){
  return key.get(this, "foo.bar")
}
```

**Comment by phillipskevin** [comment]
`return this.foo && this.foo.get('bar');` does work.

I think the confusing thing is that `this.updateDeep({ foo: { bar: "this is foo.bar" } });` doesn't trigger a `foo` change, whereas if you used `update` or `assign` it would.

I know this isn't wrong, but I didn't realize it just looking at the code.
