### ISSUE TITLE
Using listenTo with nested properties is difficult

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-define#414]
If you want to use `listenTo` in a `DefineMap` to listen to a nested property, like `person.name`, but you also need to handle when `person` changes, the code becomes pretty complicated. You have to do something like this:

```
    personName: {
      value({ listenTo, resolve }) {
        let person = null;

        const updater = (ev, name) => {
          resolve(name);
        }

        listenTo("person", (ev, p) => {
          if (person) {
            person.stopListening("name", updater);
          }

          person = p;

          person.listenTo("name", updater);
          
          updater(null, p.name);
        });
      }
    }
```

In this simple case you could just use a getter, but with more complex code, this kind of thing is necessary.

You could also make getters for any nested properties you want to use like this, something like:

```
    get personName() {
      return this.person && this.person.name;
    }
```

...and then use `listenTo("personName", ...)` but if you're only creating this extra property so you can use it with `listenTo`, it is not ideal.

I think it would be much better if we could support `listenTo("person.name", ...)` and have it automatically set up the bindings on `person` and `person.name` and handle cleanup internally.

**Comment by justinbmeyer** [comment]
The difficulty is what to do when person changes multiple times but it has the same name value. Do you callback?

**Comment by phillipskevin** [comment]
I don't think you would callback if `person.name` keeps the same value.

**Comment by justinbmeyer** [comment]
Could you do:

```js
value({listenTo, resolve}) {
  var name = value.from(this, "person.name");
  listenTo(name, resolve);
}
```

**Comment by justinbmeyer** [comment]
`can-map` did this ... but it gets weird if you have properties with `.` in them.  It also increases weight for something relatively easily done with getters.

**Comment by phillipskevin** [comment]
This does work:

```js
value({listenTo, resolve}) {
  var name = value.from(this, "person.name");
  listenTo(name, resolve);
}
```

I think this solution is fine and doing anything internally would make it hard to handle properties with `.`s in them like you mention. I'm going to close this.
