### ISSUE TITLE
includes tests need to be skipped in browsers without Array.prototype.includes

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-define#419]
These tests:
https://github.com/canjs/can-define/blob/fc905f7b61459b3991ad325c8dd300a4c00eb82b/list/list-test.js#L1490-L1538

...should be skipped in browsers that don’t support `Array.prototype.includes`.

**Comment by cherifGsoul** [comment]
@frank-dspeed DefineList is still compatible with IE11.
