### ISSUE TITLE
Consider using Proxy where available

### ISSUE THREAD

**Issue by matthewp** [canjs/can-define#44]
When Safari 10 is released Proxy will be available in every [current browser version](http://caniuse.com/#feat=proxy). Proxys would solve one problem can-define has which is the case where you have an object where the properties are not known in advance or could change without notice, such as models.  Using Proxy would make your model the same as `seal: false` but with undefined properties still being observable.

**Comment by justinbmeyer** [comment]
@matthewp not mobile I belive?

**Comment by matthewp** [comment]
It's supported on Android. Presumable iOS will get it with the new Mobile Safari release.

**Comment by justinbmeyer** [comment]
hopefully.  We'll consider it then.  `can-observable` will be viable then.

**Comment by justinbmeyer** [comment]
`can-observe` has this now.
