### ISSUE TITLE
v3: can-define/list fails to unregister event handlers in some circumstances

### ISSUE THREAD

**Issue by RyanMilligan** [canjs/can-define#455]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__ In [can-define/list/list.js](https://github.com/canjs/can-define/blob/e963a7c3adde071b6380908544d3e99a6915e1b7/list/list.js#L1538), the `offKeyValue` function creates a new function and then attempts to remove it from the event handler, which of course will never do anything. It needs to track the one created by `onKeyValue` a few lines up and remove that, in this case.

**Comment by justinbmeyer** [comment]
https://github.com/canjs/can-define/blob/e963a7c3adde071b6380908544d3e99a6915e1b7/list/list.js#L1538

**Comment by bmomberger-bitovi** [comment]
Closed via #456 and #459
