### ISSUE TITLE
DefineMap.keys unimplemented

### ISSUE THREAD

**Issue by imjoshdean** [canjs/can-define#53]
This feature from the previous `can.Map` implementation seems to have fallen by the wayside but is crucial to `can-stache` if we want to iterate over an object with `{{#expr}}` or `{{#each expr}}`.

**Comment by matthewp** [comment]
Do you mean that stache's helpers use this? Are you getting an error by any chance?

**Comment by imjoshdean** [comment]
Yes stache's helpers use this.

https://github.com/canjs/can-stache/blob/master/helpers/core.js#L115

![image](https://cloud.githubusercontent.com/assets/252054/17984565/5dcdc5c6-6ad7-11e6-9b0d-db8c9b154da7.png)

**Comment by matthewp** [comment]
Think stache can just be updated to use `Object.keys()` in this case. Will write a test for this in can-stache.

**Comment by matthewp** [comment]
This issue needs to be fixed first: https://github.com/canjs/can-define/issues/54

**Comment by matthewp** [comment]
This is fixed by https://github.com/canjs/can-stache/issues/55 and https://github.com/canjs/can-define/pull/55
