### ISSUE TITLE
DefineMap.getDefinition

### ISSUE THREAD

**Issue by matthewp** [canjs/can-define#66]
This would be useful when another library needs the definition of a property:

```js
var MyMap = DefineMap.extend({
  foo: "string"
});

var map = new MyMap();

DefineMap.getDefinition(map, "foo"); // -> { type: ... }
```

**Comment by justinbmeyer** [comment]
I might put this on `define` itself as at the end of the day, every constructor should put this in the same place.

**Comment by justinbmeyer** [comment]
The definitions on a map are always under `map._define`.  I'm not sure if this is good enough.  Closing for now.  If we need a public API, we'll re-open.
