### ISSUE TITLE
take a look at `canEvent.dispatch` in `_triggerChange`

### ISSUE THREAD

**Issue by Sinjhin** [canjs/can-define#77]
create issue for taking a look at first canEvent.dispatch in _triggerChange to see if it need to be called in the else

Take a look at the first `canEvent.dispatch.call( ... )` in the `_triggerChange` function of `list.js`.

Justin thinks it might be able to be called in the bottom else.

**Comment by justinbmeyer** [comment]
Solved as part of: https://github.com/canjs/can-define/pull/76
