### ISSUE TITLE
Make it possible for a property to be bound when any other properties are bound

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-define#85]
Say I have a stream that's tracking the behavior of another value:

``` js
MyMap = DefineMap.extend({
  previousValues: {
    stream: function(){
      return this.stream(".value").scan(function(prev, next){
        prev.push(next);
      },[])
    }
  },
  value: "*"
});
```

It's common that `previousValues` might not be used in the page, and therefore not bound and tracking changes in `value`.  When `previousValues` is eventually bound, it will be an empty Array.

To fix this, I'm proposing some form of "activeWhenAnyPropertyOnObservableIsBound" flag (obviously not that name) that `get` and `stream` can use like:

``` js
MyMap = DefineMap.extend({
  previousValues: {
    stream: function(){
      return this.stream(".value").scan(function(prev, next){
        prev.push(next);
      },[])
    },
    activeWhenAnyPropertyOnObservableIsBound: true
  },
  value: "*"
});
```

This will activate (by binding) that property when any other property is bound.  This means that if `value` is bound, `previousValues` will become "active".

This is similar conceptually to **weak** references and maps. This is why I propose the following identifier(s):
- `weakBind: true`
- `autoCompute: true`
## Technical Considerations

This might be tricky to get right with `_bindings` in https://github.com/canjs/can-event/blob/master/lifecycle/lifecycle.js.    

When `.on("value")` happens, we'll want to make sure `_eventSetup` is called and bind on any `weakBind` properties.  However, those bindings will presumably increase `_bindings`.  When `.off("value")`, we need to make sure `_eventTeardown` is called.

It's possible `can-connect/can/map` already does something like this.  I feel like I've encountered this problem before.  It might be good to formalize it.

**Comment by matthewp** [comment]
> It's common that previousValues might not be used in the page, and therefore not bound and tracking changes in value.

Is there an example use-case where it is not used in the page?

**Comment by mjstahl** [comment]
This is a really good idea (especially in the context of using streams), but I am not sure if `weakBind` or `autoCompute` really describe what is going on. 

`previousValues` isn't really weak bound because we are going to explicitly bind a callback to the change event, and have to cleanup after ourselves -- it is definitely a strong binding just like all the rest of the bindings.

Something along the lines of `alwaysBound` or `boundImplicitly` or `bindToDependents`. 

I think the idea is fantastic, I just think the nomenclature needs some work.

**Comment by BigAB** [comment]
@mjstahl I was trying to say this in a discussion at the OS meeting but, to summarize my thoughts:
`weak` reference means the reference won't prevent GC (in js at least)
`weakMap` is a `Map` that holds weak references to the keys
so in my mind
`weak` === `will not hold onto this`
So a weak binding means to me, `I will not bind to this` (but may still benefit if something else does)

Which sounds like the opposite of what this is:
As long as anything else on this instance is bound to, I will be bound too, automatically

**Comment by justinbmeyer** [comment]
@BigAB 

I think the point of contention is that I interpret `weak` as:

`weak === will ONLY hold onto this if someone else does`

So `weak binding` means:

`will ONLY bind onto this if someone else does`

**Comment by BigAB** [comment]
@justinbmeyer Yes. That is the point of contention.

**Comment by justinbmeyer** [comment]
@BigAB Thinking about it like:

```
weak === will not hold onto this
```

To me means, that `weakMap.set(key, SOMETHING)` should be a `no-op`, that `weakMap` will never hold onto that reference.  

Only by including the additional information:

```
weak === will ONLY hold onto this if someone else does
```

does the nature and behavior of `weak` have meaning.

**Comment by justinbmeyer** [comment]
- `siblingsBind: true`

**Comment by justinbmeyer** [comment]
closing for https://github.com/canjs/canjs/issues/3855
