### ISSUE TITLE
_define.definitions.property should be a regular object

### ISSUE THREAD

**Issue by roemhildtg** [canjs/can-define#86]
Currently when I access a define map's definitions, the object is not a normal object meaning it doesn't have methods like `hasOwnProperty` etc.

For example: 

``` javascript
myDefineMap._define.definitions.field.hasOwnProperty //undefined
```

It has to do with  `Object.create` [this line](https://github.com/canjs/can-define/blob/master/can-define.js#L47). Instead of `null` we should be setting it to an `Object`

**Comment by bmomberger-bitovi** [comment]
Generally speaking, when you have an object that's a key/value store (like `dataInitializers` is), especially one being enumerated over with for..in, you want to avoid giving that object a prototype chain. Though the default Object prototype's properties are non-enumerable, anything enumerable that gets added to it will cause severe issues with can-define.

http://jsbin.com/bikemubope/1/edit?html,js,output demonstrates this.

If you're working with the definitions object directly, you can always use `Object.protoype.hasOwnProperty.call(myDefineMap._define.definitions.field, "propertyName")`

**Comment by justinbmeyer** [comment]
yeah, I think we should keep it w/o the gunk on the prototype
