### ISSUE TITLE
git releases do not have an amd build

### ISSUE THREAD

**Issue by roemhildtg** [canjs/can-define#91]
[The github releases](https://github.com/canjs/can-define/releases) don't have an amd build. Some of the other packages (can-util) do though. 

I'm not sure what your build process is like but can you add amd builds to the next releases on github? For a project I'm stuck using bower.

**Comment by justinbmeyer** [comment]
Closing for https://github.com/canjs/canjs/issues/2646 at this point we are going to remove individual builds and leave it up to canjs/canjs
