### ISSUE TITLE
Document static DefineMap property in DefineList

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-define#98]
There is a static property called DefineMap used in [list.prototype.concat](https://github.com/canjs/can-define/blob/master/list/list.js#L804). I could not find any documentation around this. We should either document it or remove it.

**Comment by justinbmeyer** [comment]
Remove. Legacy of Map. Replaced by #.

**Comment by phillipskevin** [comment]
Ok, this is a duplicate of https://github.com/canjs/can-define/issues/95 then.
